version: 2
updates:
  - package-ecosystem: "maven"
    directory: "/"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: fix
      prefix-development: chore
      include: scope
    groups:
      dev-deps:
        dependency-type: "development"
      prod-deps:
        dependency-type: "production"
    ignore:
      - dependency-name: "org.jvnet.jaxb2_commons:jaxb2-basics"
      - dependency-name: "org.jvnet.jaxb2_commons:jaxb2-basics-runtime"
      - dependency-name: "org.jvnet.jaxb2_commons:jaxb2-basics-annotate"
      - dependency-name: "jakarta.xml.bind:jakarta.xml.bind-api"
      - dependency-name: "org.glassfish.jaxb:jaxb-runtime"
