stages:
- name: Build
  steps:
  - runScriptConfig:
      image: maven:3-adoptopenjdk-11
      shellScript: mvn package -DskipTests
- name: Build Docker with DIND
  steps:
  - publishImageConfig:
      dockerfilePath: ./Dockerfile
      buildContext: .
      tag: docker.dev.folio.org/mod-invoice:folijet-${CICD_EXECUTION_SEQUENCE}
      pushRemote: true
      registry: docker.dev.folio.org
- name: Deploy
  steps:
  - applyAppConfig:
      catalogTemplate: p-gh7sb:folijet-helmcharts-mod-invoice
      version: 0.1.32
      answers:
        image.repository: docker.dev.folio.org/mod-invoice
        image.tag: folijet-${CICD_EXECUTION_SEQUENCE}
      targetNamespace: folijet
      name: mod-invoice
timeout: 60
notification: {}
