#%RAML 1.0

title: Batch voucher exports
version: v1.0
protocols: [ HTTP, HTTPS ]
baseUri: http://github.com/folio-org/mod-invoice

documentation:
  - title: Batch voucher exports CRUD API
    content: This documents the API calls that can be made to manage batch voucher exports

types:
  batchVoucherExport: !include acq-models/mod-invoice-storage/schemas/batch_voucher_export.json
  batchVoucherExportCollection: !include acq-models/mod-invoice-storage/schemas/batch_voucher_export_collection.json
  errors: !include raml-util/schemas/errors.schema
  UUID:
    type: string
    pattern: ^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-5][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}$

traits:
  validate: !include raml-util/traits/validation.raml
  language: !include raml-util/traits/language.raml
  pageable:  !include raml-util/traits/pageable.raml
  searchable: !include raml-util/traits/searchable.raml

resourceTypes:
  collection: !include raml-util/rtypes/collection-with-json-response.raml
  collection-item: !include raml-util/rtypes/item-collection-with-json-response.raml

/batch-voucher/batch-voucher-exports:
  displayName: Batch-voucher-exports
  description: Manage Batch-voucher-exports
  type:
    collection:
      schemaCollection: batchVoucherExportCollection
      schemaItem: batchVoucherExport
      exampleCollection: !include acq-models/mod-invoice-storage/examples/batch_voucher_export_collection.sample
      exampleItem: !include acq-models/mod-invoice-storage/examples/batch_voucher_export.sample
  post:
    is: [validate]
  get:
    description: Get list of batch voucher exports
    is: [
      validate,
      pageable,
      searchable: {description: "with valid searchable fields: for example status", example: "status==Pending"}
    ]
  /{id}:
    uriParameters:
      id:
        description: The UUID of a batch voucher exports
        type: UUID
    displayName: Batch-voucher-exports
    description: Get, Delete or Update a specific batch-voucher-export
    type:
      collection-item:
        schema: batchVoucherExport
        exampleItem: !include acq-models/mod-invoice-storage/examples/batch_voucher_export.sample
    /upload:
      is: [language]
      post:
        description: (Re)upload the batch voucher associated with this voucher export to the configured URI, using the configured credentials
        responses:
          202:
            description: "Batch voucher export record successfully (Re)uploaded"
            body:
              application/json:
                example: !include acq-models/mod-invoice-storage/examples/batch_voucher_export.sample
          400:
            description: "Bad request, e.g. malformed request body or query parameter. Details of the error (e.g. name of the parameter or line/character number with malformed data) provided in the response."
            body:
              application/json:
                example: "unable to FTP upload of the batch voucher -- malformed JSON at 13:3"
          401:
            description: "Not authorized to perform requested action"
            body:
              application/json:
                example: "unable to FTP upload of the batch voucher -- unauthorized"
          500:
            description: "Internal server error, e.g. due to misconfiguration"
            body:
              application/json:
                example: "Internal server error, contact administrator"
    get:
      description: Return a batch-voucher-export with given {id}
      is: [validate]
    put:
      description: Update a batch-voucher-export with given {id}
      is: [validate]
    delete:
      description: Delete a batch-voucher-export with given {id}
      is: [validate]

  /scheduled:
    is: [language]
    post:
      description: Conditionally creates a batch voucher export
      responses:
        204:
          description: "Checks configuration successfully"
        202:
          description: "Batch voucher export record successfully (Re)uploaded"
          body:
            application/json:
              example: !include acq-models/mod-invoice-storage/examples/batch_voucher_export.sample
        400:
          description: "Bad request, e.g. malformed request body or query parameter. Details of the error (e.g. name of the parameter or line/character number with malformed data) provided in the response."
          body:
            application/json:
              example: "unable to FTP upload of the batch voucher -- malformed JSON at 13:3"
        401:
          description: "Not authorized to perform requested action"
          body:
            application/json:
              example: "unable to FTP upload of the batch voucher -- unauthorized"
        500:
          description: "Internal server error, e.g. due to misconfiguration"
          body:
            application/json:
              example: "Internal server error, contact administrator"

