#%RAML 1.0

title: Voucher
version: v0.1
protocols: [ HTTP, HTTPS ]
baseUri: https://github.com/folio-org/mod-invoice

documentation:
  - title: Voucher API
    content: This documents the API calls that can be made to manage vouchers

types:
  voucher: !include acq-models/mod-invoice-storage/schemas/voucher.json
  errors: !include raml-util/schemas/errors.schema
  UUID:
    type: string
    pattern: ^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-5][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}$

traits:
  validate: !include raml-util/traits/validation.raml
  language: !include raml-util/traits/language.raml
  pageable:  !include raml-util/traits/pageable.raml
  searchable: !include raml-util/traits/searchable.raml

resourceTypes:
  get-only: !include raml-util/rtypes/get-only.raml

/voucher:
  /vouchers/{id}:
      uriParameters:
        id:
          description: The UUID of an voucher
          type: UUID
      displayName: voucher
      description: Get specific voucher
      type:
        get-only:
          schema: voucher
          exampleCollection: !include acq-models/mod-invoice-storage/examples/voucher.sample
      get:
        description: Return an voucher with given {id}